### ISSUE TITLE
Add observations to ADF via variable defaults file

### ISSUE THREAD

**Issue by nusbaume** [NCAR/ADF#100]
### New feature type

New infrastructure or infrastructure enhancement

### What is this new feature?

The variable defaults file (`adf_variable_defaults.yaml`) could be used to indicate which observational datasets a particular model variable should be compared against.  This would allow for full model vs. obs capabilities in the ADF, at least until Intake-ESM is brought into the framework, and provides an avenue for a user to access an observational dataset without having to immediately add it to an Intake catalog in the future.

Finally, please note that this will likely result in the removal of the `obs_type_list` from the ADF config file.

### Assistance required?

No, I will make a PR when the feature is ready

**Comment by andrewgettelman** [comment]
I think this is a good idea, and Jesse and I have discussed it.

I think that all we would need is attributes for each variable to specify:
1. Observation file name
2. Observation variable name
3. Observation unit conversion

Regarding time samples:

Right now we mostly have 2D (single level) or 3D (multi level) climatologies with only 1 time sample per file (monthly, seasonal or annual). Could we just make a monthly file and have the software deal with seasonal and annual? OR: we just assume the previous convention and look for a month (01-12) season (DJF, JJA, etc) or 'ANN'). 

I guess software needs to assume we are interpolating horizontally and vertically (in pressure)?
