### ISSUE TITLE
Include polar stereographic plots

### ISSUE THREAD

**Issue by brianpm** [NCAR/ADF#101]
### New feature type

New plot and/or plot enhancement

### What is this new feature?

Polar stereographic plots like in the old AMWG diagnostics. Contour values of mean fields and their difference for northern and southern hemispheres.

### Assistance required?

No, I will make a PR when the feature is ready

**Comment by nusbaume** [comment]
I believe this issue was resolved by PR #103.  If that is not the case then please feel free to re-open this issue.
