### ISSUE TITLE
Bug in Taylor Plots

### ISSUE THREAD

**Issue by andrewgettelman** [NCAR/ADF#108]
### ADF run type

Model vs. Model

### What happened?

There is a bug in the taylor plots: there is no standard deviation in the xarray weighted method. 

This occurs here:
https://github.com/NCAR/ADF/blob/main/scripts/plotting/cam_taylor_diagram.py#L372

A fix would be to write a weighted_std routine (as with the weighted_correlation routine). 

### ADF Hash you are using

187c929

### What machine were you running the ADF on?

CISL machine

### What python environment were you using?

NPL (CISL machines only)

### Extra info

Brian has provided a fix to this, which Andrew has implemented locally. Probably not working yet. 

I will try to check in Brian's running modification to a branch in my repo and link to it in this issue.

**Comment by andrewgettelman** [comment]
Okay, I have implemented a fix that runs, but it needs to be checked by @brianpm since I'm not sure it is doing the right thing yet. Please go to:

https://github.com/andrewgettelman/ADF/tree/taylor_bug

Specifically: 

https://github.com/andrewgettelman/ADF/blob/taylor_bug/scripts/plotting/cam_taylor_diagram.py

This runs but produces a standard deviation that **MAY** be too low (see figure):
![amwg_taylor_diagram_ANN](https://user-images.githubusercontent.com/9616874/154163578-74a3be51-8d51-4c0d-98c3-2a2f9cc22f1a.png)

**Comment by brianpm** [comment]
Ooof. Yeah, that doesn't seem right. I'll try to double check the weighted standard deviation calculation.

**Comment by brianpm** [comment]
I have identified the bug. Turns out writing a function that quickly during a hackathon isn't necessarily a good idea. I normalized the weights incorrectly.

The correct function is this:

```python

def weighted_std(x, weights):
    """Weighted standard deviation.
    
    x -> xr.DataArray
    weights -> array-like of weights, probably xr.DataArray

    If weights is not the same shape as x, will use `broadcast_like` to 
    create weights array.

    Returns the weighted standard deviation of the full x array.

    """
    xshape = x.shape
    wshape = weights.shape
    if xshape != wshape:
        wa = weights.broadcast_like(x)
    else:
        wa = weights
    mean_x = x.weighted(weights).mean()
    dev_x = x - mean_x
    swdev = (weights * dev_x**2).sum()
    total_weights = wa.where(x.notnull()).sum()
    return np.sqrt(swdev / total_weights)
```

I'm getting a PR ready.
