### ISSUE TITLE
Wiki page Example of CAM vs CAM instructions is empty

### ISSUE THREAD

**Issue by bitterbark** [NCAR/ADF#109]
### ADF run type

Model vs. Model

### What happened?

When I click on the link in the wiki for the Cam vs Cam example, it is empty. I think this has happened before but I don't think I have the capability to revert it.
<img width="1259" alt="Screen Shot 2022-02-17 at 4 01 58 PM" src="https://user-images.githubusercontent.com/30841536/154586171-b0b07c14-5271-4034-a078-1d31a212e624.png">

### ADF Hash you are using

doesn't matter

### What machine were you running the ADF on?

Other (please explain below)

### What python environment were you using?

Other (please explain below)

**Comment by nusbaume** [comment]
Hi @bitterbark , I think I just fixed it.  Can you test the link whenever you get the chance to see if it works on your end?  Thanks!

**Comment by bitterbark** [comment]
Sorry for the delay, it is fine now. Thanks!
