### ISSUE TITLE
Need ability to plot 3-D variables on 2-D maps when given pressure levels to use

### ISSUE THREAD

**Issue by nusbaume** [NCAR/ADF#121]
### New feature type

New plot and/or plot enhancement, New regridding method or regridding enhancement

### What is this new feature?

Currently the lat/lon plotting script only accepts 2-D input variables, which must be 2-D in the model output file themselves.  However, it would be beneficial to have the ability to specify pressure levels on which to generate lat/lon maps of 3-D variables (e.g. `U` or `Q`).   This will require a relatively-expensive vertical interpolation, which should be done once during the re-gridding stage, instead of multiple times during the plotting stage.  

The pressure levels themselves could be passed into the ADF using either the variable defaults file, or as arguments in the config file itself (ideally both).

### Assistance required?

Yes, I will need some assistance before making a PR

### Extra info

Bringing this issue to the attention of @juliecaron , @WillyChap, and @judithberner , based on the quick discussion we all had at the last hackathon.

**Comment by WillyChap** [comment]
@nusbaume: 
Functionality for plotting lat/lon plots on desired pressures levels for _Model_ vs. _Model_  is in the path shown below. Largely following @juliecaron 's vector plotting. The model level interpolation is surprisingly fast (I haven't actually clocked it, but O(1 second)), however this could slow down given larger data.  

**/glade/scratch/wchapman/developer_ADF/ADF/scripts/plotting/global_latlon_map.py** 

There are a few further concerns

1. after my vertical interpolation with geocats, the xarrays are returned as chunked dask array's, I then have to load them to get xarray's else the pf.plot_map_and_save() function grinds to a hault. This could slow down the process 
2. I have hard coded variables **provided_levs** and **levs_des** which will have to be inherited from the .yaml file .. this hasn't been done yet. 
3. I have yet to implement any error handling if hybrid model levels do not exist (I'm not sure the work around for this).
4. The colorbar is not divergent given fields that are both positive and negative.. I'm sure plotting **kwargs can fix this, just don't know how/where. 
5. need to add website functionality.
