### ISSUE TITLE
Scaling observations

### ISSUE THREAD

**Issue by andrewgettelman** [NCAR/ADF#124]
### New feature type

New climatology method or climatology enhancement

### What is this new feature?

I was wondering if we can scale observations the way we scale data using adf_variable_defaults.yaml (my favorite file!)?

There is a scale_factor and add_offset.  I assume we could add that for the observations too?

I'm thinking of separate variables so things could come in differently (obs_scale_factor, obs_offset)

I guess if I got some guidance over where the scale factor is applied to model data I could copy it over for observations. 

With some guidance here I am happy to help add the feature. 

### Assistance required?

Yes, I will need some assistance before making a PR

**Comment by brianpm** [comment]
I agree we will need this feature. I'm not sure what the best approach is. It would be good if we implement this in a way that will be relatively unobtrusive at the `scripts` level. By that I mean, provide the scale/offset information in the variable defaults file, but deal with it in the ADF core functions rather than force the analysis/plotting scripts to check.  I guess that is difficult if the observations are provided as time series and a script wants to use the time series directly. So one option is to assume (dictate) that observations be provided as climatologies. Another option is to provide something along the lines of a function adf_load_dataset that would do the scaling (and other adjustments) based on config file information.

**Comment by andrewgettelman** [comment]
I was thinking of applying the scaling and offset the same way it is applied to the model data. I was thinking it would be done at the same time in the same way, and then it shouldn't matter, but would give us the freedom to easily adjust observations. 

I see now (and I should have looked before sorry) that each plotting routine applies this to the data after it is read in and averaged. So I can do this I think. There is a block for unit transformations. So a conditional should do it. Quoting plotting/zonal_mean.py:

Existing:

`                # APPLY UNITS TRANSFORMATION IF SPECIFIED:
                # NOTE: looks like our climo files don't have all their metadata
                mdata = mdata * vres.get("scale_factor",1) + vres.get("add_offset", 0)
                # update units
                mdata.attrs['units'] = vres.get("new_unit", mdata.attrs.get('units', 'none'))

                # Do the same for the baseline case if need be:
                if not adfobj.compare_obs:
                    odata = odata * vres.get("scale_factor",1) + vres.get("add_offset", 0)
                    # update units
                    odata.attrs['units'] = vres.get("new_unit", odata.attrs.get('units', 'none'))
`

I think I could just add:
`
               #Or for observations
                else:
                    odata = odata * vres.get("obs_scale_factor",1) + vres.get("obs_add_offset", 0)
                    # update units
                    odata.attrs['units'] = vres.get("obs_new_unit", odata.attrs.get('units', 'none'))
`

Would that work? Does the framework need to specify that I am defining something? I bet not.... Going to try it.


This would not have any issue with how the observations are provided (climo or timeseries) that I can see.

**Comment by andrewgettelman** [comment]
Yes, it works. Will code it up into the 3 routines that use it and add to the PR....

**Comment by brianpm** [comment]
Thanks, @andrewgettelman ! I think this approach is practical. We might revisit at some point to reduce needed code in the `plotting_scripts` and make it easier for users to add their own custom scripts. But I agree that right now we should use your approach to get ADF running for CAM7 purposes.

**Comment by andrewgettelman** [comment]
Okay, this is added to 3 routines (global_latlon_map.py, polar_map.py, zonal_mean.py).

Part of #122 . Will close the issue now.
