### ISSUE TITLE
Add climo years for both cases to output directory name 

### ISSUE THREAD

**Issue by justin-richling** [NCAR/ADF#150]
### New feature type

Other (please explain below)

### What is this new feature?

When running model vs model ADF, it would be helpful to display the start and end years for both cases in the created directory, especially for the scenarios where they aren't the same. This would also follow the old AMWG diagnostics naming convention:

![Screen Shot 2022-04-20 at 8 03 19 AM (3)](https://user-images.githubusercontent.com/56696811/164248640-a32b014b-4477-4d3c-b061-d8939288e983.png)

### Assistance required?

No, I will make a PR when the feature is ready

**Comment by nusbaume** [comment]
This issue has been closed via PRs #148 and #151.   Of course if the problem still exists then feel free to re-open it!
