### ISSUE TITLE
Need equatorial cross section

### ISSUE THREAD

**Issue by brianpm** [NCAR/ADF#169]
### New feature type

New plot and/or plot enhancement

### What is this new feature?

The request is to add capability similar to old AMWG diagnostics set 4a: "Vertical contour (XZ) plots of DJF, MAM, JJA, SON and ANN meridional means". 

### Assistance required?

No, I will make a PR when the feature is ready

### Extra info

This is from our initial assessment of desired features (in the spreadsheet). I talked with Meg (whose name is attached), and she's not planning to get to it.

I should be able to provide a new plotting script that adds this basic feature, and I will at least provide methods to do both "XZ" (i.e., longitude-pressure) plots as well as just "X" (longitude) plots. 

**stretch goal**
I may also explore a generalization to allow arbitrary cross sections (assuming regular gridded data). I've got code that does it fine, but the complication is how to let the user specify the cross section, variables to use, and possibly other choices that need to be made (e.g., interpolation vs nearest-neighbor)

**Comment by nusbaume** [comment]
This issue has been resolved by PR #188 , so closing now.
