### ISSUE TITLE
Adding a set with timeseries

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/ADF#170]
### New feature type

New plot and/or plot enhancement

### What is this new feature?

We have started to look at coupled runs and I think it would be useful to have the option to add timeseries of global average ANN. 

For instance, timeseries of RESTOM, SST, TS like:
![Screen Shot 2022-05-23 at 9 34 34 AM](https://user-images.githubusercontent.com/9723220/169855521-4cbcb12d-22eb-437d-b8f4-bbb639416ae5.png)
 

### Assistance required?

Yes, I am requesting a new feature but won't have time to develop it

**Comment by andrewgettelman** [comment]
Good idea. I would suggest that these line plots be set up to be able to do multiple runs (either 2 runs or multi-case)......

**Comment by brianpm** [comment]
I agree, this is a good feature to add. As a start, I suppose global means make the most sense. I'd expand to also have land and ocean separately, and then hemispheric averages (and / or arbitrary regions, but this starts to become confusing for the website generation and the config file).

**Comment by adagj** [comment]
Hi! I wonder if the timeseries are included in the current version of ADF? And if so, how do we run it? Thanks for a great tool by the way :-)

**Comment by brianpm** [comment]
#334 will address this (at least as a starter)

**Comment by justin-richling** [comment]
Closed with #334
