### ISSUE TITLE
Consistency across plotting scripts

### ISSUE THREAD

**Issue by justin-richling** [NCAR/ADF#176]
I've noticed that the plotting functions for the polar maps could use some consistency compared to the other plot types. 

For example, the plotting function for polar maps currently reside in the ```polar_map.py``` file, where as the plotting functions for the other plot types reside in the ```plotting_function.py``` file. 

Also for the polar maps, the ```savefig``` and ```plt.close``` calls are not included in the ```make_polar_plot``` function but instead get called after the ```make_polar_plot``` call.

I can clean these up if there are no specific reason why they are laid out this way now.

**Comment by nusbaume** [comment]
I am not aware of any reason why the polar plots are organized differently compared to the other plots (I think that was just how it was brought in originally).  So I am happy if you want to clean them up and make them similar to the other plotting scripts.

Also pinging @brianpm in case he has a different opinion, as he was the one who did most of the polar plots development.

**Comment by brianpm** [comment]
I don't object. There's kind of a question of what *should* be in `plotting_functions.py` versus be in stand-alone scripts. This has been ambiguous since the beginning, and I don't think there's really a right answer. Maybe sometime soon we should have a discussion about what standards we want to impose around standard plots that we "support."

**Comment by brianpm** [comment]
I think making the vector plots have a consistent look and feel with the regular lat/lon plots is a good idea!

**Comment by brianpm** [comment]
I just started a discussion around the broader issue of how we support plotting scripts. It is here: https://github.com/NCAR/ADF/discussions/181
