### ISSUE TITLE
CAM diagnostics only works with Python version 3.4 or later

### ISSUE THREAD

**Issue by nusbaume** [NCAR/ADF#2]
Due to the presence of certain libraries (in particular the "pathlib" library), the CAM diagnostics only works with Python version 3.4 (or later).  

Ideally, these library calls should be replaced with older methods to allow for a wider range of python versions to be used, including Python version 2.7.

**Comment by brianpm** [comment]
I'd argue that even supporting back to 3.4 is pretty generous, since it was released in 2014. Since the python 2 series is end-of-lifed already (https://pythonclock.org), I don't think it is worth any effort to support it.
