### ISSUE TITLE
AMWG Tables aren't getting formatted correctly in html file creation

### ISSUE THREAD

**Issue by justin-richling** [NCAR/ADF#217]
### ADF run type

Model vs. Model

### What happened?

The AMWG tables for the website are not getting formatted correctly when going from pandas DataFrame to HTML.

Currently the ADF is formatting all values in the ```to_html()``` call to pandas data frame being brought over in the ```web_data``` variable in ```adf_web.py```.  However it loses precision for numbers larger than two digits. 

For example, if a mean value is 288.156, the table formats it to 288, but if the mean is 44.7, it retains that precision. Right now the ```float_format``` value that goes into the ```to_html()``` call is ```.3g``` meaning it retains only 3 important digits, hence why 288.15 returns 288 and something like 0.000815 would retain 0.000815

#### Example:

![adf_0 3g_format](https://user-images.githubusercontent.com/56696811/199741074-9f88a634-9085-48eb-8887-e37581422c9d.png)

### ADF Hash you are using

2b3eca8

### What machine were you running the ADF on?

CISL machine, CGD machine

### What python environment were you using?

NPL (CISL machines only)

### Extra info

I am testing a solution that finds what range for the mean and statistical table values and sets float format based on those in ```amwg_table.py``` before it gets to ```adf_web.py```.

**Comment by brianpm** [comment]
What is the preferred format? Looks like it is easy enough to specify it, but we have the problem that the table could have giant and minuscule numbers. Probably we need to use scientific notation for numbers beyond some number of digits. 
```python
start = 0.0000000005588
for i in range(20):
    n = (10**i) * start
    print(f"{n:5.5g}")
#
5.588e-10
5.588e-09
5.588e-08
5.588e-07
5.588e-06
5.588e-05
0.0005588
0.005588
0.05588
0.5588
5.588
55.88
558.8
 5588
55880
5.588e+05
5.588e+06
5.588e+07
5.588e+08
5.588e+09
```

see, e.g., https://stackoverflow.com/questions/29108341/pandas-dataframe-float-formatting

This is probably what you were suggesting?

**Comment by justin-richling** [comment]
Yeah, the range of values like TAU compared to PSL is what makes it hard to have a one size fits all format, like you mentioned above. What you have is basically what I'm testing. And it's really just the unpredictable way pandas dataframes get put into HTML; it sometimes has a mind of it's own.
