### ISSUE TITLE
Create Chemistry Diagnostic Table 

### ISSUE THREAD

**Issue by rrbuchholz** [NCAR/ADF#236]
### New feature type

New table and/or analytic calculation

### What is this new feature?

Evaluate chemistry mean values of select species.

Example of the old chemistry table is attached.
![Screenshot at 2023-03-29 11-22-58](https://user-images.githubusercontent.com/12089161/228618707-5613cd6f-b049-45c4-8360-806896afcbc5.png)

### Assistance required?

Yes, I will need some assistance before making a PR

### Extra info

chemistry diagnostic

**Comment by justin-richling** [comment]
Here is a progress report on the Chemistry tables so far:
[https://project.cgd.ucar.edu/projects/ADF/chem-diags/tables/html_table/amwg_table_Chemistry.html](https://project.cgd.ucar.edu/projects/ADF/chem-diags/tables/html_table/amwg_table_Chemistry.html)
