### ISSUE TITLE
Climo year grab fails for non cam.h0 files

### ISSUE THREAD

**Issue by bitterbark** [NCAR/ADF#263]
### ADF run type

Model vs. Model

### What happened?

This line relies on the standard cam.h0 format, and fails for other files (eg. $case.cam.h2.0021-05-01-00000.nc)
>     case_climo_yrs_str = sorted(np.unique([i.stem[-7:-3] for i in files_list]))

### ADF Hash you are using

b12f7c4

### What machine were you running the ADF on?

CISL machine

### What python environment were you using?

NPL (CISL machines only)

### Extra info

I'm happy to help debug

**Comment by justin-richling** [comment]
Closed with [#275](https://github.com/NCAR/ADF/pull/275)
