### ISSUE TITLE
When comparing runs with different vertical grid: tape recorder plot is buggy 

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/ADF#301]
### ADF run type

Model vs. Model

### What happened?

I am comparing a L58 with a L42 run: (https://webext.cgd.ucar.edu/BLT1850/b.e23_alpha16g.BLT1850.ne30_t232_L42.082b/atm/b.e23_alpha16g.BLT1850.ne30_t232_L42.082b_2_21_vs_b.e23_alpha16g.BLT1850.ne30_t232.082b_2_21/html_img/plot_page_Q_TapeRecorder_ANN_Special_Mean.html)

### ADF Hash you are using

52fe742

### What machine were you running the ADF on?

CISL machine

### What python environment were you using?

NPL (CISL machines only)

**Comment by justin-richling** [comment]
This is interesting behavior, some case it seems to work, other it only woks if plotting indivually:

![Q_TapeRecorder_ANN_Special_Mean_wtf](https://github.com/user-attachments/assets/d027ac6b-5801-472b-bff2-762e19d339d6)


![Q_TapeRecorder_ANN_Special_Mean_0](https://github.com/user-attachments/assets/d1599cfd-174d-4692-8882-eb90b8781aef)


![Q_TapeRecorder_ANN_Special_Mean_1](https://github.com/user-attachments/assets/e7758523-8a05-4c46-9de8-f7725b2293ac)
