### ISSUE TITLE
Add option to use percent change plot instead of difference plots when applicable

### ISSUE THREAD

**Issue by shawnusaf** [NCAR/ADF#331]
### New feature type

New plot and/or plot enhancement

### What is this new feature?

This feature would allow the difference plot that is included in several of the plotting types to be a percent change plot instead.  This would be more useful than a difference plot for composition variables.

### Assistance required?

Yes, I am requesting a new feature but won't have time to develop it

### Extra info

May have time to work on this - I do have a prototype rough version of this feature that works to some degree.

**Comment by justin-richling** [comment]
Closed with PR #339
