### ISSUE TITLE
Adjust default Tape Recorder color bar range 

### ISSUE THREAD

**Issue by shawnusaf** [NCAR/ADF#332]
### New feature type

New plot and/or plot enhancement

### What is this new feature?

The tape recorder plot needs to have the default color table tweaked so that the upper end of the range doesn't saturate at 3.0 e-6 kg/kg.  It should be set to something like 4.0 or possibly even 5.0.  

### Assistance required?

Yes, I am requesting a new feature but won't have time to develop it

**Comment by justin-richling** [comment]
Closed with PR #339
