### ISSUE TITLE
Allow for a list of cases to support multi-run analysis

### ISSUE THREAD

**Issue by nusbaume** [NCAR/ADF#40]
Currently the diagnostics package  can only process one simulation (case) at a time.  However, as brought up by @andrewgettelman, there are various scientific reasons why it would be helpful to process multiple cases all at once, compare them all to the same observations or baseline, and then plot them all on the same figure.

In order to facilitate this new capability, the diagnostics package should be able to take in a list of cases that can then all be processed during the same diagnostics run, thus providing a single data collection that can be used to generated the relevant multi-case figures.

**Comment by andrewgettelman** [comment]
A simple way to do this is to make it non-destructive: have a list of cases, but we can map case[0] = control and case[1] = test, or something like that. So if a plot looks for a list, it is there. 

In addition, there could be a list of which 'group' (e.g. ensemble) a case belongs to: so if you had 5 future and 5 present day cases, a diagnostic could separate the cases by group (or ensemble). 

The thought is to make this as easy and lightweight as possible to put in the framework, and then diagnostics can just use it.
