### ISSUE TITLE
"start_year" and "end_year" only modify time series files

### ISSUE THREAD

**Issue by nusbaume** [NCAR/ADF#42]
The current diagnostics config files make it sound as if the variables `start_year` and `end_year` set over which years a climatology will be calculated for a particular model case.  However, they in fact only set the length of the generated time series files, which means if someone already has time series files then these variables won't do anything, as the entire time series will be used each time to calculate the climatologies.

To remedy this issue, the `create_climo` and `averaging_example.py` script (as well as any future averaging scripts) should be modified to sub-select the time series such that only the user-specified year range is involved in the calculation of the climatologies.

**Comment by brianpm** [comment]
Is this addressed by https://github.com/NCAR/ADF/pull/117 ?

**Comment by nusbaume** [comment]
@brianpm Yes, good catch!  Closing this issue now.
