### ISSUE TITLE
Put together an example of running this from a Jupyter Notebook

### ISSUE THREAD

**Issue by mgrover1** [NCAR/ADF#56]
As was mentioned in the meeting, it would be good to have an example of running this from a Jupyter Notebook

**Comment by nusbaume** [comment]
I forgot to mention this in the meeting, but it would probably make the most sense to convert `run_adf_diag` into a notebook, as it would help reveal more of the actual diagnostics workflow (while still being notebook friendly, I think).

**Comment by nusbaume** [comment]
Unless of course there was an alternative plan for notebook conversion (I am definitely not much of a notebook expert)!
