### ISSUE TITLE
Need version-specific "stable" conda environment

### ISSUE THREAD

**Issue by nusbaume** [NCAR/ADF#69]
Currently the conda environment provided for the ADF doesn't specify external package versions, which means the latest/greatest version will be used when the environment is created.  This means that if there are upstream conflicts in those packages the ADF can be broken in a way that can be quite difficult to debug by the average user.

Thus to avoid this situation, it would be better to have the default conda environment use specific package versions that are known to work with the ADF.  This will allow most users/developers to work with the ADF independent of upstream package changes.

**Comment by bitterbark** [comment]
Sounds good. Would it also be possible to name the ADF conda environments
with the ADF version? With other packages, when I am trying to upgrade, I
end up losing my capability of running the previous one.

**Comment by nusbaume** [comment]
@bitterbark Yep, can do!  I'll tag the next PR (which will include this change), and will include the tag number in the conda environment name (so any future environments will have a different tag number and thus won't overwrite this one).
