### ISSUE TITLE
File names of ADF-created timeseries should match the CESM timeseries file naming standard

### ISSUE THREAD

**Issue by phillips-ad** [NCAR/ADF#77]
ADF created timeseries should include the date range in the file names. At present, timeseries that are created are named:
$cam_case_name.ncrcat.$variable.nc
To allow users to know the dates within the file, to allow future CVDP integration, and as the ADF will likely be used to form timeseries files (as it's easier than other methods), I propose the files be named the same as standard CESM timeseries files:
$cam_case_name.h0.$variable.YYYYMM-YYYYMM.nc

**Comment by brianpm** [comment]
This is a good suggestion. We currently use NCO's `ncrcat` to make the time series files. I suppose that we could construct the file name by trusting that the input files (h0 or other CAM files) would have the correct times in their names. The most authoritative source for CESM naming: https://www.cesm.ucar.edu/models/cesm2/naming_conventions.html

Based on this... I **think** this would work inside of `adf_diag.py`:

```
hist_files = sorted(files_list)
# Check if time series directory exists, and if not, then create it:
# Use pathlib to create parent directories, if necessary.
Path(ts_dir).mkdir(parents=True, exist_ok=True)
# INPUT NAME TEMPLATE: $CASE.$scomp.[$type.][$string.]$date[$ending] 
first_file_split = hist_files[0].split(".")
if first_file_split[-1] == "nc":
    time_string_start = first_file_split[-2]
else:    
    time_string_start = first_file_split[-1]
last_file_split = hist_files[-1].split(".")
if last_file_split[-1] == "nc":
    time_string_finish = last_file_split[-2]
else:    
    time_string_finish = last_file_split[-1]
time_string = "-".join([time_string_start, time_string_finish])

# OUTPUT NAME TEMPLATE:  $cam_case_name.h0.$variable.YYYYMM-YYYYMM.nc
ofilnam = ".".join([case_name, "h0", var, time_string, "nc" ])

# ... some code in here ....
for var in var_list:
    #Create full path name:
    ts_outfil_str = ts_dir + os.sep + ofilnam
    # ALTERNATIVE USING pathlib: 
    # ts_outfil_str = Path(ts_dir) / ofilnam
```

This would probably require a few changes downstream to correct any instances where we use the old file names. I'm not sure if there are any/many of those.
