### ISSUE TITLE
fake bug

### ISSUE THREAD

**Issue by tribbia** [NCAR/ADF#86]
### ADF run type

Model vs. Model

### What happened?

A bug happened! not really

### ADF Hash you are using

35c75be

### What machine were you running the ADF on?

CISL machine

### What python environment were you using?

NPL (CISL machines only)

### Extra info

I am pretending to have a bug . I will not change code just add a comment.

**Comment by nusbaume** [comment]
@tribbia I have applied a fake bug fix to this problem, so am closing it now (but if you want to experiment with it in the future feel free to re-open it).  Thanks!
