### ISSUE TITLE
Speed up computing climos 

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/ADF#92]
### New feature type

Other (please explain below)

### What is this new feature?

I tried to use ADF to compute climos from the ne30-L58 runs. I was trying to compute a 10-year climo on the years 1980-1989

The script didn't go anywhere in 12 hours. I talked to Jesse who recommended that I added an issue. 

Examples of history files are at:
/glade/scratch/hannay/archive/f.e21.FWscHIST.ne30_L48_BL10_cam6_3_035.tphysac_reorder_zm2_tau7200.001.hf

### Assistance required?

Yes, I am requesting a new feature but won't have time to develop it

**Comment by brianpm** [comment]
This seems odd. Looking at those files, I don't see a reason that it should be slower than the example data we've been using. @cecilehannay , were you trying to process many, many variables? 

The only other thing I can think of is that there wasn't enough memory available for `ncrcat` to work efficiently. I'll try to reproduce the issue, but I don't have any extra time until after Christmas, probably.

**Comment by cecilehannay** [comment]
I was trying to process ALL the variables in the h0 files.

No emergency. I just want to add this to the issues as Jesse recommended.
Also, maybe I was doing something wrong.

**Comment by cecilehannay** [comment]
@nusbaume : It was just hanging. First I thought it was slow. And I came back the following day and it was still at the same place. I will try it again and I will let you know.

**Comment by nusbaume** [comment]
@cecilehannay That sounds like it might be a "real" bug.  If you are on the CISL machines can you point me to your config (XXX.yaml) file?

**Comment by nusbaume** [comment]
@swrneale You should be able to look in the directories specified by either `cam_ts_loc` or `cam_climo_loc` under the `diag_cam_climo` section and see if any files are present.  If there are and they are slowly being added then it is likely just running slow.  However, if there are no files at all then the ADF is likely hanging.

Also, if it is hanging can you point me to your config (XXX.yaml) file?  That might help me figure out what exactly is going wrong.  Thanks!
